// /framework/core/src/types/client.ts
import type * as jtv from "@mojotech/json-type-validation";

type IsAny<T> = 0 extends 1 & T ? true : false;
type NoAny<T> = IsAny<T> extends true ? never : T;

/**
 * Prettifies complex types (like intersections) to show a single flattened object
 * in the IDE hover experience.
 */
export type Prettify<T> = {
	[K in keyof T]: T[K];
} & {};

// biome-ignore lint/suspicious/noExplicitAny: Necessary for functional inference mapping
type GetPayload<T> = T extends { encode: (p: infer P) => any }
	? IsAny<P> extends true
		? unknown
		: P
	: unknown;

/**
 * Represents the fundamental structure of a Daml Template as generated by Daml Codegen.
 */
export interface DamlTemplate<Payload = unknown> {
	templateId: string;
	decoder: jtv.Decoder<Payload>;
	encode: (payload: Payload) => unknown;
}

/**
 * Interface for SQL-based filtering when querying PQS layers.
 */
export interface PqsFindOptions<Payload> {
	where?: Partial<Payload> | { OR?: Partial<Payload>[]; AND?: Partial<Payload>[] };
	limit?: number;
	orderBy?: { [K in keyof Payload]?: "asc" | "desc" };
}

/**
 * Interface representing a fully materialized Contract fetched from Canton.
 * It contains both the unique Ledger identifier and the actual business Payload.
 */
export interface Contract<Payload> {
	contractId: string;
	payload: Prettify<Payload>;
}

/**
 * Operations available on a single Contract once a User context is established.
 */
export interface CommandQueryOperations<Payload> {
	/**
	 * Submits a Ledger Command to create a new contract.
	 *
	 * The provided payload is automatically validated against the Daml schema
	 * and formatted to the network's standard encoding.
	 *
	 * @param payload The raw JavaScript object representing the Template arguments.
	 *                Note: Passing 'any' is strictly forbidden to prevent type leaks.
	 */
	create: <P extends Payload>(payload: NoAny<P>) => Promise<Prettify<Contract<Payload>>>;

	/**
	 * Queries active contracts utilizing high-performance SQL engines.
	 *
	 * Supports complex filtering equivalent to typical ORM find constraints,
	 * ensuring millisecond-level responsiveness for large datasets.
	 *
	 * @param options Query and filter constraints.
	 */
	findMany: (options?: Prettify<PqsFindOptions<Payload>>) => Promise<Prettify<Contract<Payload>>[]>;

	/**
	 * Returns a singular contract from the Ledger query store by its ID.
	 *
	 * @param contractId Ledger ID of the target contract.
	 */
	findById: (contractId: string) => Promise<Prettify<Contract<Payload>> | null>;

	/**
	 * Exercises a choice on an active contract.
	 *
	 * @param contractId Ledger ID of the target contract.
	 * @param choiceName Name of the choice to exercise.
	 * @param choiceArgument Arguments for the choice.
	 */
	exercise: (contractId: string, choiceName: string, choiceArgument: unknown) => Promise<unknown>;

	/**
	 * Archives an active contract (shorthand for the Archive choice).
	 *
	 * @param contractId Ledger ID of the target contract.
	 */
	archive: (contractId: string) => Promise<unknown>;
}

export type ConstructNexusApi<T extends Record<string, unknown>> = {
	[K in keyof T as T[K] extends {
		templateId: string;
		// biome-ignore lint/suspicious/noExplicitAny: Necessary to match all Daml Template patterns
		encode: (p: any) => any;
	}
		? K
		: never]: CommandQueryOperations<GetPayload<T[K]>>;
};

/**
 * Interface defining what a Server Plugin can do.
 */
export interface NexusServerPlugin<T extends Record<string, unknown> = Record<string, unknown>> {
	id: string;
	onInit?: (config: NexusServerConfig<T>) => void;
	/** Intercepts operations to route them to different backends (Ledger vs PQS) */
	extendOperations?: (
		baseOps: CommandQueryOperations<unknown>,
		ctx: { partyId: string; token?: string; templateId: string; template: DamlTemplate<unknown> },
	) => CommandQueryOperations<unknown>;
}

/**
 * Interface defining what a Server Plugin can do.
 */
export interface NexusServerPlugin<T extends Record<string, unknown> = Record<string, unknown>> {
	id: string;
	onInit?: (config: NexusServerConfig<T>) => void;
	/** Intercepts operations to route them to different backends (Ledger vs PQS) */
	extendOperations?: (
		baseOps: CommandQueryOperations<unknown>,
		ctx: { partyId: string; token?: string; templateId: string; template: DamlTemplate<unknown> },
	) => CommandQueryOperations<unknown>;
}

export interface NexusServerConfig<T extends Record<string, unknown>> {
	types: T;
	plugins?: NexusServerPlugin<Record<string, unknown>>[];
}

/**
 * A highly typed Nexus Universal Client root object.
 */
export interface NexusUniversalClient<T extends Record<string, unknown>> {
	/**
	 * Establishes context and authorization for impending Ledger workflows.
	 * @param partyId Targeted participant executing the workflow.
	 * @param token Optional OAuth or JWT token to authenticate operations.
	 */
	withUser: (partyId: string, token?: string) => ConstructNexusApi<T>;
}
