// /framework/core/src/types/client.ts

/**
 * Universal Decoder Interface representing JTV functions output by daml2js.
 */
export interface JtvDecoder<T> {
	run: (val: unknown) => { ok: true; result: T } | { ok: false; error: { message: string } } | T;
}

/**
 * Represents the fundamental structure of a Daml Template as generated by Daml Codegen.
 */
export interface DamlTemplate<Payload = unknown, _Key = unknown> {
	templateId: string;
	decoder: JtvDecoder<Payload>;
	encode: (payload: Payload) => unknown;
}

/**
 * Interface for SQL-based filtering when querying PQS layers.
 */
export interface PqsFindOptions<Payload> {
	where?: Partial<Payload> | { OR?: Partial<Payload>[]; AND?: Partial<Payload>[] };
	limit?: number;
	orderBy?: { [K in keyof Payload]?: "asc" | "desc" };
}

/**
 * Operations available on a single Contract once a User context is established.
 */
export interface CommandQueryOperations<Payload> {
	/**
	 * Submits a Ledger Command to create a new contract. Payload is automatically
	 * validated using JTV and formatted to Daml-LF Standard Encoding.
	 * @param payload The raw JavaScript object representing the Template arguments
	 * @returns The resulting creation payload from the network.
	 */
	create: (payload: Payload) => Promise<unknown>;

	/**
	 * Queries PQS utilizing SQL engines for exceptionally fast retrieval.
	 * Supports generic filtering equivalent to typical ORM find constraints.
	 * @param options Query and filter constraints
	 */
	findMany: (options?: PqsFindOptions<Payload>) => Promise<Payload[]>;

	/**
	 * Returns a singular contract from the Ledger query store.
	 * @param contractId Ledger ID of the target contract.
	 */
	findById: (contractId: string) => Promise<Payload | null>;
}

/**
 * The core type transformer that traverses developer-provided daml2js
 * exports and constructs a Universal Proxy API containing strongly-typed operations.
 */
export type ConstructNexusApi<T extends Record<string, unknown>> = {
	[K in keyof T as T[K] extends DamlTemplate<unknown> ? K : never]: T[K] extends DamlTemplate<
		infer Payload
	>
		? CommandQueryOperations<Payload>
		: never;
};

/**
 * Connection Details defining where the SDK communicates.
 */
export interface NexusClientConfig {
	ledgerUrl: string; // Target HTTP JSON API (e.g., http://localhost:3975)
	pqsUrl: string; // Target Postgres connection string (e.g., postgres://user:pass@localhost:5432)
}

/**
 * A highly typed Nexus Universal Client root object.
 */
export interface NexusUniversalClient<T extends Record<string, unknown>> {
	/**
	 * Establishes context and authorization for impending Ledger workflows.
	 * @param partyId Targeted participant executing the workflow.
	 * @param token Optional OAuth or JWT token to authenticate operations.
	 */
	withUser: (partyId: string, token?: string) => ConstructNexusApi<T>;
}
